language: php

dist: xenial

services:
  - mysql

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - COMPOSER_FLAGS=""
  - COMPOSER_FLAGS="--prefer-lowest"

before_install:
  - mysql -e 'create database `test`;'

install:
  - travis_retry composer update --no-interaction --no-suggest --prefer-dist --prefer-stable $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit